name: pub_update_checker
description: Check if your dart script package is up to date in one line.
version: 1.2.0
homepage: https://github.com/Rexios80/pub_update_checker

environment:
  sdk: ">=2.15.0 <3.0.0"

dependencies:
  yaml: ^3.1.0
  pub_api_client: ^2.2.1
  pub_semver: ^2.1.0

dev_dependencies:
  rexios_lints: ^5.0.0
